---
- name: Install Nginx Redis Lua Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'lua-nginx-redis', 'redis-server', 'redis-tools' ]
  become: yes
  notify: Reload Nginx

- name: Copy Lua Nginx configuration
  copy:
    src: files/lua.conf
    dest: /etc/nginx/conf.d/lua.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload Nginx
